source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak"
plug "alexherbo2/connect.kak"
plug "andreyorst/fzf.kak"
plug "andreyorst/powerline.kak" defer "powerline" %{
    powerline-seperator triangle
    set-option global powerline_format 'powerline-format git bugname filetype mode_info line_column position'
      powerline-toggle line_column off
            powerline-theme gruvbox
}

map global normal <c-p> ': fzf-mode<ret>'
map global user a -docstring "This is a test" :w
